# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serverConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=63)),
                ('config_value', models.CharField(max_length=63)),
            ],
        ),
    ]
